theme: minima
title: Your awesome title
email: your-email@domain.com
author: Mr. GitHub User
description: "Write an awesome description for your new site here. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
twitter_username: jekyllrb
github_username:  jekyll

collections:
  posts:
    permalink: /posts/:title
