title: 0-fold Cross-Validation
author: Alexej Gossmann
email: alexej.go@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Blogging aspirations: machine learning, statistics, deep learning, math, theory, application, creativity.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: agisga
    github: agisga
    rss: feed.xml
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: alexejgossmann
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    mastodon:
      - username: 0foldcv
        instance: mathstodon.xyz
    # - username: jekyll2
    #   instance: example.com

disqus:
  shortname: 0foldcv

# From https://jekyllrb.com/docs/usage/:
# If you want to build for your production environment:
# * Set your production URL in `_config.yml` e.g. `url: https://example.com.`
# * Run `JEKYLL_ENV=production bundle exec jekyll build`
url: https://0foldcv.com

# Set the permalink structure globally
permalink: /:title/

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md
#  - microblog.md
# "Blog" and "Microblog" links are included by default, see `_includes/header.html`

# Build settings
theme: minima

plugins:
 - jemoji
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-scholar

# Jekyll-scholar configuration
scholar:
  style: apa #ieee-with-url
  source: ./_bibliography
  bibliography: references.bib
