title: 0-fold Cross-Validation
author: Alexej Gossmann
email: alexej.go@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Blogging aspirations: machine learning, statistics, deep learning, math, theory, application, coding, creativity.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: agisga
    github: agisga
    rss: feed.xml
    # dribbble: jekyll
    facebook: alexej.yexela
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: alexejgossmann
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    mastodon:
      - username: 0foldcv
        instance: mathstodon.xyz
    # - username: jekyll2
    #   instance: example.com

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: agisga

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-94080131-1

# From https://jekyllrb.com/docs/usage/:
# If you want to build for your production environment:
# * Set your production URL in `_config.yml` e.g. `url: https://example.com.`
# * Run `JEKYLL_ENV=production bundle exec jekyll build`
url: https://www.alexejgossmann.com

# Set the permalink structure globally
permalink: /:title/

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md
#  - microblog.md
# "Blog" and "Microblog" links are included by default, see `_includes/header.html`

# Build settings
theme: minima

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar
  - jekyll-paginate-v2

# Jekyll-paginate-v2 configuration
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page:num/' # Pages are index.html inside this folder (default)
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

# Jekyll-scholar configuration
scholar:
  style: apa #ieee-with-url
  sort_by: year, month
  order: descending
  source: ./_bibliography
  bibliography: references.bib  # name of the default bibliography used to add references within posts
  bibliography_template: bib  # bib.html in _layouts
  repository: ./assets/pdf  # When generating bibliographies, Jekyll-Scholar will look in that folder to see if it contains a filename matching each entry's BibTeX key: if it does, the path to that file will be exposed to the bibliography template as the link property.
